### ISSUE TITLE
config_map_name is not defined

### ISSUE THREAD

**Issue by afeiszli** [opendatahub-io/jupyterhub-singleuser-profiles#3]
@vpavlin Deployed JupyterHub as per the readme, using 'master' branch, on OpenShift Dedicated 3.11. Selected s2i-minimal-notebook:3.6, and clicked 'Spawn'. Get "Error: name 'config_map_name' is not defined". Logs from JupyterHub pod:

[D 2019-02-11 18:13:07.155 JupyterHub base:603] Initiating spawn for afeiszli
--
  | [D 2019-02-11 18:13:07.155 JupyterHub base:609] 0/100 concurrent spawns
  | [D 2019-02-11 18:13:07.155 JupyterHub base:612] 0 active servers
  | [E 2019-02-11 18:13:07.245 JupyterHub user:477] Unhandled error starting afeiszli's server: name 'config_map_name' is not defined
  | [D 2019-02-11 18:13:07.253 JupyterHub user:578] Deleting oauth client jupyterhub-user-afeiszli
  | [E 2019-02-11 18:13:07.264 JupyterHub pages:148] Failed to spawn single-user server with form
  | Traceback (most recent call last):
  | File "/opt/app-root/lib/python3.6/site-packages/jupyterhub/handlers/pages.py", line 146, in post
  | await self.spawn_single_user(user, options=options)
  | File "/opt/app-root/lib/python3.6/site-packages/jupyterhub/handlers/base.py", line 705, in spawn_single_user
  | timedelta(seconds=self.slow_spawn_timeout), finish_spawn_future
  | File "/opt/app-root/lib/python3.6/site-packages/jupyterhub/handlers/base.py", line 626, in finish_user_spawn
  | await spawn_future
  | File "/opt/app-root/lib/python3.6/site-packages/jupyterhub/user.py", line 489, in spawn
  | raise e
  | File "/opt/app-root/lib/python3.6/site-packages/jupyterhub/user.py", line 405, in spawn
  | await maybe_future(spawner.run_pre_spawn_hook())
  | File "/opt/app-root/lib/python3.6/site-packages/jupyterhub/spawner.py", line 716, in run_pre_spawn_hook
  | return self.pre_spawn_hook(self)
  | File "/opt/app-root/src/.jupyter/jupyterhub_config.py", line 244, in setup_environment
  | spawner.single_user_profiles.load_profiles(username=spawner.user.name)
  | File "/opt/app-root/lib/python3.6/site-packages/jupyterhub_singleuser_profiles/profiles.py", line 76, in load_profiles
  | print("Could not find config map %s" % config_map_name)
  | NameError: name 'config_map_name' is not defined

![image](https://user-images.githubusercontent.com/31018251/52584414-a3cffe00-2df7-11e9-8948-811ed5e36d2d.png)

**Comment by vpavlin** [comment]
Fixed
