### ISSUE TITLE
Add ability to configure maximum number of GPUs for users

### ISSUE THREAD

**Issue by vpavlin** [opendatahub-io/jupyterhub-singleuser-profiles#77]
An admin should be able to configure the limit for GPU allocation - somewhere in the main ConfigMap set

```
gpu:
  limit: NUMBER
  style: input/checkbox
```

UI should then respect the style and enforce the limit

WDYT? @mroman-redhat @altruistcoder

**Comment by mroman-redhat** [comment]
Solved by: #111 and #123
